[package]
name = "initialize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grovedb = { git = "https://github.com/dashevo/grovedb.git", branch = "develop" }
